#!/usr/bin/env node
/** Sign or verify every downloadable first-party entry in index.json.
 *
 * Signing reads a private key file generated by ServerKit's
 * scripts/sign-extension.mjs. The key path is mandatory and is never printed.
 * Verification uses only trusted-publishers.json and is safe for CI.
 *
 *   node scripts/sign_first_party.mjs sign --key <private-key.json> [--out-dir <dir>]
 *   node scripts/sign_first_party.mjs verify
 */
import {
  createHash,
  createPrivateKey,
  createPublicKey,
  sign as edSign,
  verify as edVerify,
} from 'node:crypto';
import {
  mkdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const INDEX_PATH = join(ROOT, 'index.json');
const TRUST_PATH = join(ROOT, 'trusted-publishers.json');
const MARKER = Buffer.from('ED');
const SPKI_PREFIX = Buffer.from('302a300506032b6570032100', 'hex');

const fail = (message) => {
  process.stderr.write(`error: ${message}\n`);
  process.exit(1);
};

const parseArgs = (args) => {
  const out = { command: args[0], key: null, outDir: null };
  for (let i = 1; i < args.length; i += 1) {
    if (args[i] === '--key') out.key = args[++i];
    else if (args[i] === '--out-dir') out.outDir = args[++i];
    else fail(`unknown argument: ${args[i]}`);
  }
  return out;
};

const rawPublicKey = (key) => {
  const der = createPublicKey(key).export({ type: 'spki', format: 'der' });
  return der.subarray(der.length - 32);
};

const keyNum = (raw) => createHash('sha256').update(raw).digest().subarray(0, 8);
const sha256 = (blob) => createHash('sha256').update(blob).digest('hex');

async function download(entry) {
  const response = await fetch(entry.source, {
    headers: { 'User-Agent': 'serverkit-extensions-signing' },
    redirect: 'follow',
  });
  if (!response.ok) {
    throw new Error(`${entry.slug}: download returned HTTP ${response.status}`);
  }
  return Buffer.from(await response.arrayBuffer());
}

function firstPartyArtifacts(index) {
  return index.extensions.filter((entry) => entry.first_party && !entry.bundled);
}

async function signIndex(keyPath, outDir) {
  if (!keyPath) fail('sign requires --key <private-key.json>');
  const keyFile = JSON.parse(readFileSync(keyPath, 'utf8'));
  if (keyFile.algorithm !== 'ed25519' || !keyFile.secret_key_pkcs8 || !keyFile.public_key) {
    fail('key file must contain key_id, ed25519 public_key, and secret_key_pkcs8');
  }
  const privateKey = createPrivateKey({
    key: Buffer.from(keyFile.secret_key_pkcs8, 'base64'),
    type: 'pkcs8',
    format: 'der',
  });
  const derivedPublic = rawPublicKey(privateKey);
  const declaredPublic = Buffer.from(keyFile.public_key, 'base64');
  if (!derivedPublic.equals(declaredPublic)) {
    fail('private key does not match the key file public_key');
  }

  const trusted = JSON.parse(readFileSync(TRUST_PATH, 'utf8')).keys || [];
  const pinned = trusted.find((entry) => entry.key_id === keyFile.key_id);
  if (!pinned || pinned.public_key !== keyFile.public_key) {
    fail(`key '${keyFile.key_id}' is not pinned with the same public key in trusted-publishers.json`);
  }

  const index = JSON.parse(readFileSync(INDEX_PATH, 'utf8'));
  const artifacts = firstPartyArtifacts(index);
  if (!artifacts.length) fail('index has no downloadable first-party extensions');
  if (outDir) mkdirSync(outDir, { recursive: true });

  for (const entry of artifacts) {
    const blob = await download(entry);
    const actual = sha256(blob);
    if (actual !== entry.sha256) {
      fail(`${entry.slug}: sha256 mismatch (index ${entry.sha256}, download ${actual})`);
    }
    const envelope = Buffer.concat([
      MARKER,
      keyNum(derivedPublic),
      edSign(null, blob, privateKey),
    ]);
    entry.signature = envelope.toString('base64');
    entry.publisher_key_id = keyFile.key_id;
    if (outDir) {
      writeFileSync(join(outDir, `${basename(new URL(entry.source).pathname)}.minisig`),
        `${entry.signature}\n`, { mode: 0o600 });
    }
    process.stdout.write(`signed ${entry.slug} ${entry.version} (${blob.length} bytes)\n`);
  }
  index.updated = new Date().toISOString().slice(0, 10);
  writeFileSync(INDEX_PATH, `${JSON.stringify(index, null, 2)}\n`);
}

async function verifyIndex() {
  const index = JSON.parse(readFileSync(INDEX_PATH, 'utf8'));
  const trustedFile = JSON.parse(readFileSync(TRUST_PATH, 'utf8'));
  const trusted = new Map((trustedFile.keys || []).map((entry) => [entry.key_id, entry]));
  const artifacts = firstPartyArtifacts(index);
  if (!artifacts.length) fail('index has no downloadable first-party extensions');

  for (const entry of artifacts) {
    if (!entry.signature || !entry.publisher_key_id) {
      fail(`${entry.slug}: first-party artifact is unsigned`);
    }
    const keyEntry = trusted.get(entry.publisher_key_id);
    if (!keyEntry || keyEntry.algorithm !== 'ed25519') {
      fail(`${entry.slug}: publisher key '${entry.publisher_key_id}' is not trusted`);
    }
    const publicRaw = Buffer.from(keyEntry.public_key, 'base64');
    const envelope = Buffer.from(entry.signature, 'base64');
    if (envelope.length !== 74 || !envelope.subarray(0, 2).equals(MARKER)) {
      fail(`${entry.slug}: malformed signature envelope`);
    }
    if (!envelope.subarray(2, 10).equals(keyNum(publicRaw))) {
      fail(`${entry.slug}: signature key does not match publisher_key_id`);
    }
    const blob = await download(entry);
    const actual = sha256(blob);
    if (actual !== entry.sha256) {
      fail(`${entry.slug}: sha256 mismatch (index ${entry.sha256}, download ${actual})`);
    }
    const publicKey = createPublicKey({
      key: Buffer.concat([SPKI_PREFIX, publicRaw]),
      type: 'spki',
      format: 'der',
    });
    if (!edVerify(null, blob, publicKey, envelope.subarray(10))) {
      fail(`${entry.slug}: signature does not match the published artifact`);
    }
    process.stdout.write(`verified ${entry.slug} ${entry.version} (${blob.length} bytes)\n`);
  }
}

const args = parseArgs(process.argv.slice(2));
if (args.command === 'sign') await signIndex(args.key, args.outDir);
else if (args.command === 'verify') await verifyIndex();
else fail('usage: sign_first_party.mjs <sign|verify> [--key path] [--out-dir path]');
